server:
  shutdown: graceful
  http2:
    enabled: true

logging:
  level:
    root: info

spring:
  application:
    name: api-keys
  webflux:
    base-path: /keys/v1
  cache:
    type: none
  redis:
    client-type: lettuce
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 500
        min-idle: 5

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,metrics"
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
      env: ${spring.profiles.active}
      instanceId: ${random.uuid}
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readynessstate:
      enabled: true

opentracing:
  jaeger:
    enabled: true
    service-name: ${spring.application.name}-${spring.profiles.active}
    log-spans: false
    http-sender:
      url: http://localhost:14268/api/traces
    probabilistic-sampler:
      sampling-rate: 1 # 1 = 100%, 0.5 = 50%, etc.
  spring:
    cloud:
      jdbc:
        enabled: false
      redis:
        enabled: true
    web:
      skip-pattern: /actuator.*

redis:
  root-key: payment
  publicKeySwapTime: 60 # in seconds
  ttl:
    default: 60 # in minutes
    partner-public-keys: 1440 # in minutes

interceptor:
  mdc-interceptor:
    enabled: true # Mapped Diagnostic Context (MDC)
